#SmoothChat configuration
#Tue Jun 02 21:12:33 CEST 2026
chatBackgroundOpacity=0.5
chatOpacity=1.0
chatOpenSlideEnabled=true
chatOpenSlideTicks=10.0
fadeInEnabled=true
fadeInTicks=50.0
messageSlideOffset=100.0
messageSlideTicks=5.0
