name = "All Of Babric"
author = "DanyGames2014"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91d7b684c1e9aba77b1ce10f2c74ea471fc1d823b74861b18603561c3c0d7bfa"

[versions]
fabric = "0.19.2"
minecraft = "b1.7.3"
unsup = "1.2.4"

[options]
acceptable-game-versions = ["b1.7.3"]
