name = "All Of Babric"
author = "DanyGames2014"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ec372fc19c44e9bcdd66f9a64704de61cf5b72ef44de68e43415d8629d2d88d"

[versions]
fabric = "0.17.2"
minecraft = "b1.7.3"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["b1.7.3"]
