name = "All Of Babric"
author = "DanyGames2014"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b71acabd55094f10b586c2b596d4b9fe9526abe890641bf8c692d873248a1fa"

[versions]
fabric = "0.18.4"
minecraft = "b1.7.3"
unsup = "1.2.0-pre4"

[options]
acceptable-game-versions = ["b1.7.3"]
